global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'portfolio-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8085']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']